Add parsing and serializing tests with intermediate turtle results to check

diff --git a/tests/feeds/Makefile.am b/tests/feeds/Makefile.am
--- a/tests/feeds/Makefile.am
+++ b/tests/feeds/Makefile.am
@@ -22,6 +22,8 @@
 
 TEST_RSS=test01.rss test02.rss test03.rss
 TEST_ATOMS=$(TEST_RSS:.rss=.atom)
+TEST_TTLS=$(TEST_RSS:.rss=.ttl)
+OUT_TTLS=$(TEST_RSS:.rss=-result.ttl)
 OUT_ATOMS=$(TEST_RSS:.rss=-result.atom)
 EXTRA_ATOMS=
 
@@ -61,15 +63,50 @@ check-local:: check-feeds
 endif
 
 
+@RAPTOR_PARSER_RSS_TRUE@check-local:: check-parse-feed
 @RAPTOR_SERIALIZER_ATOM_TRUE@check-local:: check-serialize-atom
 
 check-feeds: build-rapper $(TEST_FILES)
 
-check-serialize-atom $(TEST_ATOMS): $(TEST_RSS)
+check-parse-feed $(TEST_TTLS): $(TEST_RSS)
 	@set +e; result=0; \
-	echo "Testing Atom XML serializing"; \
+	echo "Testing Feed parsing"; \
 	for test in $(TEST_RSS); do \
 	  name=`basename $$test .rss` ; \
+	  turtle="$$name.ttl"; \
+	  expected="$$name-result.ttl"; \
+	  opts="-f writeBaseURI=0"; \
+	  if test $$name = test01; then \
+	    baseuri="http://example.org/whatsnew"; \
+	  elif test $$name = test02; then \
+	    baseuri="http://example.org/news/"; \
+	  elif test $$name = test03; then \
+	    baseuri="http://example.org"; \
+	  fi; \
+	  opts="-q -i rdfxml -o turtle $$opts -O $$baseuri"; \
+	  echo $(ECHO_N) "Checking $$test $(ECHO_C)"; \
+	  $(RAPPER) $$opts file:$(srcdir)/$$test > $$turtle 2> errors.log; \
+	  status=$$?; \
+	  if test $$status != 0; then \
+	    echo "FAILED with code $$status"; \
+	    echo "$(RAPPER) $$opts file:$(srcdir)/$$test"; \
+	    cat errors.log ; \
+	  elif cmp $(srcdir)/$$expected $$turtle >/dev/null 2>&1; then \
+	    echo "ok"; \
+	  else \
+	    echo "FAILED"; \
+	    echo "$(RAPPER) $$opts file:$(srcdir)/$$test"; \
+	    diff -u $(srcdir)/$$expected $$turtle; result=1; \
+	  fi; \
+	  rm -f errors.log ; \
+	done; \
+	set -e; exit $$result
+
+check-serialize-atom $(TEST_ATOMS): $(TEST_TTLS)
+	@set +e; result=0; \
+	echo "Testing Atom XML serializing"; \
+	for test in $(TEST_TTLS); do \
+	  name=`basename $$test .ttl` ; \
 	  atom="$$name.atom"; \
 	  expected="$$name-result.atom"; \
 	  opts="-f writeBaseURI=0 -f rssTriples=atom-triples"; \
@@ -81,7 +118,7 @@ check-serialize-atom $(TEST_ATOMS): $(TEST_RSS)
 	  elif test $$name = test03; then \
 	    baseuri="http://example.org"; \
 	  fi; \
-	  opts="-q -i rdfxml -o atom $$opts -O $$baseuri"; \
+	  opts="-q -i turtle -o atom $$opts -O $$baseuri"; \
 	  echo $(ECHO_N) "Checking $$test $(ECHO_C)"; \
 	  $(RAPPER) $$opts file:$(srcdir)/$$test > $$atom 2> errors.log; \
 	  status=$$?; \
