Add test04 and test05 atom parsing to turtle.  Update test suite to show errors better and use ECHO macros

diff --git a/tests/feeds/Makefile.am b/tests/feeds/Makefile.am
--- a/tests/feeds/Makefile.am
+++ b/tests/feeds/Makefile.am
@@ -20,24 +20,30 @@
 # 
 # 
 
-# Input RSS 1.0 files
-TEST_RSS=test01.rss test02.rss test03.rss
+# Input RDF/XML (atom model) files - rdfxml parser
+TEST_IN_RDF_ATOMS= test01.rdf test02.rdf test03.rdf
+# Input Atom 1.0 (atom model) files - rss-tag-soup parser
+TEST_IN_ATOMS= test04.atom test05.atom
 
 # Output files in Turtle (after parsing) and Atom (after serializing) 
-TEST_TTLS=$(TEST_RSS:.rss=.ttl)
-TEST_ATOMS=$(TEST_RSS:.rss=.atom)
+OUT_RDF_TTLS= $(TEST_IN_RDF_ATOMS:.rdf=.ttl)
+OUT_ATOM_TTLS= $(TEST_IN_ATOMS:.atom=.ttl)
+OUT_RDF_ATOMS= $(TEST_IN_RDF_ATOMS:.rdf=.atom)
 
 # Expected results for above
-OUT_TTLS=$(TEST_RSS:.rss=-result.ttl)
-OUT_ATOMS=$(TEST_RSS:.rss=-result.atom)
+EXPECTED_TTLS= $(OUT_RDF_TTLS:.ttl=-result.ttl)
+EXPECTED_ATOMS= $(OUT_RDF_ATOMS:.atom=-result.atom)
 
+# Files generated during testing (to delete/clean)
+OUT_TTLS = $(OUT_RDF_TTLS) $(OUT_ATOM_TTLS)
+OUT_ATOMS = $(OUT_RDF_ATOMS)
 
-ALL_TEST_FILES= \
-	$(TEST_ATOMS)
+EXTRA_DIST = \
+$(TEST_IN_RDF_ATOMS) $(TEST_IN_ATOMS) \
+$(EXPECTED_TTLS) $(EXPECTED_ATOMS) \
+atom.rng atom.rnc
 
-EXTRA_DIST = $(TEST_RSS) $(OUT_ATOMS) atom.rng atom.rnc
-
-CLEANFILES = $(TEST_ATOMS) $(TEST_TTLS) errors.log
+CLEANFILES = $(OUT_ATOMS) $(OUT_TTLS) errors.log
 
 RAPPER = $(top_builddir)/utils/rapper
 
@@ -46,8 +52,12 @@ build-rapper:
 
 FEED_TESTS=
 
+if RAPTOR_PARSER_RDFXML
+FEED_TESTS += check-rdfxml-to-turtle
+endif
+
 if RAPTOR_PARSER_RSS
-FEED_TESTS += check-parse-feed
+FEED_TESTS += check-atom-to-turtle
 endif
 
 if RAPTOR_SERIALIZER_ATOM
@@ -60,11 +70,13 @@ endif
 
 check-local: build-rapper $(FEED_TESTS)
 
-check-parse-feed $(TEST_TTLS): $(TEST_RSS)
+# Parse from RDF/XML and Serialize to Turtle
+check-rdfxml-to-turtle: $(TEST_IN_RDF_ATOMS)
 	@set +e; result=0; \
-	echo "Testing Feed parsing"; \
-	for test in $(TEST_RSS); do \
-	  name=`basename $$test .rss` ; \
+	$(ECHO) "Testing RDF/XML to Turtle"; \
+	for test in $?; do \
+	  parser=rdfxml; \
+	  name=`basename $$test .rdf` ; \
 	  turtle="$$name.ttl"; \
 	  expected="$$name-result.ttl"; \
 	  opts="-f writeBaseURI=0"; \
@@ -75,29 +87,63 @@ check-parse-feed $(TEST_TTLS): $(TEST_RSS)
 	  elif test $$name = test03; then \
 	    baseuri="http://example.org"; \
 	  fi; \
-	  opts="-q -i rdfxml -o turtle $$opts -O $$baseuri"; \
-	  echo $(ECHO_N) "Checking $$test $(ECHO_C)"; \
+	  opts="-q -i $$parser -o turtle $$opts -O $$baseuri"; \
+	  $(ECHO) $(ECHO_N) "Checking $$test $(ECHO_C)"; \
 	  $(RAPPER) $$opts file:$(srcdir)/$$test > $$turtle 2> errors.log; \
 	  status=$$?; \
 	  if test $$status != 0; then \
-	    echo "FAILED with code $$status"; \
-	    echo "$(RAPPER) $$opts file:$(srcdir)/$$test"; \
+	    $(ECHO) "FAILED with code $$status"; \
+	    $(ECHO) "$(RAPPER) $$opts file:$(srcdir)/$$test"; \
 	    cat errors.log ; \
 	  elif cmp $(srcdir)/$$expected $$turtle >/dev/null 2>&1; then \
-	    echo "ok"; \
+	    $(ECHO) "ok"; \
 	  else \
-	    echo "FAILED"; \
-	    echo "$(RAPPER) $$opts file:$(srcdir)/$$test"; \
+	    $(ECHO) "FAILED"; \
+	    $(ECHO) "$(RAPPER) $$opts file:$(srcdir)/$$test"; \
 	    diff -u $(srcdir)/$$expected $$turtle; result=1; \
 	  fi; \
 	  rm -f errors.log ; \
 	done; \
 	set -e; exit $$result
 
-check-serialize-atom $(TEST_ATOMS): $(TEST_TTLS)
+# Parser from Atom and Serialize to Turtle
+check-atom-to-turtle: $(TEST_IN_ATOMS)
 	@set +e; result=0; \
-	echo "Testing Atom XML serializing"; \
-	for test in $(TEST_TTLS); do \
+	$(ECHO) "Testing Atom to Turtle"; \
+	for test in $?; do \
+	  parser=rss-tag-soup; \
+	  name=`basename $$test .atom` ; \
+	  turtle="$$name.ttl"; \
+	  expected="$$name-result.ttl"; \
+	  opts="-f writeBaseURI=0"; \
+	  baseuri="http://www.example.org/blog/"; \
+	  if test $$name = test04; then \
+	    baseuri="http://www.example.org/blog/"; \
+	  fi; \
+	  opts="-q -i $$parser -o turtle $$opts -O $$baseuri"; \
+	  $(ECHO) $(ECHO_N) "Checking $$test $(ECHO_C)"; \
+	  $(RAPPER) $$opts file:$(srcdir)/$$test > $$turtle 2> errors.log; \
+	  status=$$?; \
+	  if test $$status != 0; then \
+	    $(ECHO) "FAILED with code $$status"; \
+	    $(ECHO) "$(RAPPER) $$opts file:$(srcdir)/$$test"; \
+	    cat errors.log ; \
+	  elif cmp $(srcdir)/$$expected $$turtle >/dev/null 2>&1; then \
+	    $(ECHO) "ok"; \
+	  else \
+	    $(ECHO) "FAILED"; \
+	    $(ECHO) "$(RAPPER) $$opts file:$(srcdir)/$$test"; \
+	    diff -u $(srcdir)/$$expected $$turtle; result=1; \
+	  fi; \
+	  rm -f errors.log ; \
+	done; \
+	set -e; exit $$result
+
+# Parser from Turtle and Serialize to Atom
+check-serialize-atom: $(OUT_RDF_TTLS)
+	@set +e; result=0; \
+	$(ECHO) "Testing Turtle to Atom XML"; \
+	for test in $(OUT_RDF_TTLS); do \
 	  name=`basename $$test .ttl` ; \
 	  atom="$$name.atom"; \
 	  expected="$$name-result.atom"; \
@@ -111,18 +157,18 @@ check-serialize-atom $(TEST_ATOMS): $(TEST_TTLS)
 	    baseuri="http://example.org"; \
 	  fi; \
 	  opts="-q -i turtle -o atom $$opts -I $$baseuri -O $$baseuri"; \
-	  echo $(ECHO_N) "Checking $$test $(ECHO_C)"; \
+	  $(ECHO) $(ECHO_N) "Checking $$test $(ECHO_C)"; \
 	  $(RAPPER) $$opts file:$(srcdir)/$$test > $$atom 2> errors.log; \
 	  status=$$?; \
 	  if test $$status != 0; then \
-	    echo "FAILED with code $$status"; \
-	    echo "$(RAPPER) $$opts file:$(srcdir)/$$test"; \
+	    $(ECHO) "FAILED with code $$status"; \
+	    $(ECHO) "$(RAPPER) $$opts file:$(srcdir)/$$test"; \
 	    cat errors.log ; \
 	  elif cmp $(srcdir)/$$expected $$atom >/dev/null 2>&1; then \
-	    echo "ok"; \
+	    $(ECHO) "ok"; \
 	  else \
-	    echo "FAILED"; \
-	    echo "$(RAPPER) $$opts file:$(srcdir)/$$test"; \
+	    $(ECHO) "FAILED"; \
+	    $(ECHO) "$(RAPPER) $$opts file:$(srcdir)/$$test"; \
 	    diff -u $(srcdir)/$$expected $$atom; result=1; \
 	  fi; \
 	  rm -f errors.log ; \
@@ -136,12 +182,21 @@ SUFFIXES = .rng .rnc
 .rnc.rng:
 	trang $? $@
 
-check-validate-atom: $(srcdir)/atom.rng $(TEST_ATOMS)
-	@echo "Validating Atom XML with RelaxNG"; \
-	for atom in $(TEST_ATOMS); do \
-	  echo "$$atom"; \
-	  jing $(srcdir)/atom.rng $$atom; \
+check-validate-atom: $(srcdir)/atom.rng $(OUT_ATOMS) $(TEST_IN_ATOMS)
+	@set +e; result=0; \
+	$(ECHO) "Validating Atom XML with RelaxNG"; \
+	for atom in $(OUT_ATOMS) $(TEST_IN_ATOMS); do \
+	  $(ECHO) $(ECHO_N) "Validating $$atom $(ECHO_C)"; \
+	  jing $(srcdir)/atom.rng $$atom > errors.log 2>&1; \
+	  status=$$?; \
+	  if test $$status != 0; then \
+	    $(ECHO) "FAILED with code $$status"; result=1; \
+	    $(ECHO) jing $(srcdir)/atom.rng $$atom; \
+	    sed -e "s,^.*$$atom,$$atom," errors.log ; \
+	  else \
+	    $(ECHO) "ok"; \
+          fi; \
+          rm -f errors.log; \
 	done
-# or xmllint --relaxng atom.rng --noout $$atom
 
 endif
